#!/bin/sh
# Diode Server
# Copyright 2021-2024 Diode
# Licensed under the Diode License, Version 1.1
ulimit -n 120000
export ERL_CRASH_DUMP_BYTES=5000000000
export ERL_EPMD_ADDRESS=127.0.0.1
export MIX_ENV=prod
mix deps.get
export ELIXIR_ERL_OPTIONS='+sbwt none -noinput -noshell -sname diode_light +A 8'
exec elixir -S mix run --no-halt
