#!/bin/bash

if [[ $1 == "elevated" ]]; then
	shift
	if [[ $SNAP_UID -ne "0" ]]; then
		echo "You need to be super user"
		exit 1
	fi
fi

export ERL_INETRC="$SNAP_USER_DATA/erl_inetrc"
export RELEASE_DISTRIBUTION=name

if [[ $1 != "start" ]]; then
	cd $SNAP_REAL_HOME
else
	host=$(hostname).diode
	echo "diode_node@$host" > $SNAP_USER_DATA/node
	echo "{host, {127,0,0,1}, [\"$host\", \"diode_node@$host\"]}." > $ERL_INETRC
	echo "{edns,0}." >> $ERL_INETRC
	echo "{lookup, [file, dns]}." >> $ERL_INETRC
fi

export RELEASE_NODE=`cat $SNAP_USER_DATA/node`
exec ${SNAP}/bin/diode_node $*
